version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel_songs_db_tk6i
      DB_USERNAME: laravel_songs_db_tk6i_user
      DB_PASSWORD: secret

  db:
    image: postgres:15
    container_name: laravel-db
    environment:
      POSTGRES_USER: laravel_songs_db_tk6i_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel_songs_db_tk6i
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel_songs_db_tk6i_user -d laravel_songs_db_tk6i"]
      interval: 10s
      timeout: 5s
      retries: 5
