name: CI/CD Laravel OTAP

on:
  push:
    branches:
      - main
      - dev
      - test
<<<<<<< HEAD
=======
      - acc
>>>>>>> acc
  pull_request:

jobs:
  # -------------------------
  # Lint
  # -------------------------
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Pint (lint)
        run: vendor/bin/pint --test || exit 1

  # -------------------------
  # Test (met database)
  # -------------------------
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: laravel_test
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
<<<<<<< HEAD
      - name: Use example env
        run: cp .env.example .env
      - name: Generate app key
        run: php artisan key:generate
      - name: Wait for DB
        run: |
=======

      - name: Use CI environment
        run: |
          if [[ "${GITHUB_REF}" != "refs/heads/dev" ]]; then
            cp .env.ci .env
          fi

      - name: Generate app key
        run: php artisan key:generate

      # Alleen DB + migraties voor test, acc, main
      - name: Setup DB and migrate
        if: github.ref != 'refs/heads/dev'
        run: |
          sudo service mysql start || true
>>>>>>> acc
          for i in {1..15}; do
            if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
              echo "DB is up!"
              break
            fi
            echo "Waiting for DB..."
            sleep 5
          done
<<<<<<< HEAD
      - name: Run migrations
        run: php artisan migrate --force
=======
          php artisan migrate --force

>>>>>>> acc
      - name: Run tests
        run: php artisan test

  # -------------------------
  # Deploy naar Render
  # -------------------------
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/acc'
    steps:
      - uses: actions/checkout@v3
<<<<<<< HEAD
      - name: Deploy to Render
=======

      - name: Deploy
>>>>>>> acc
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            SERVICE_ID=${{ secrets.RENDER_SERVICE_ID_PROD }}
<<<<<<< HEAD
          elif [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            SERVICE_ID=${{ secrets.RENDER_SERVICE_ID_DEV }}
          elif [[ "${GITHUB_REF}" == "refs/heads/test" ]]; then
            SERVICE_ID=${{ secrets.RENDER_SERVICE_ID_TEST }}
          else
            echo "No deployment for this branch."
            exit 0
          fi

          echo "Deploying branch ${GITHUB_REF} to Render service $SERVICE_ID..."
=======
          elif [[ "${GITHUB_REF}" == "refs/heads/acc" ]]; then
            SERVICE_ID=${{ secrets.RENDER_SERVICE_ID_ACC }}
          fi

          echo "Deploying branch ${GITHUB_REF} to service $SERVICE_ID"
>>>>>>> acc
          curl -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
               -H "Accept: application/json" \
               -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
