name: CI/CD Laravel OTAP

on:
  push:
    branches:
      - main
      - dev
      - test
      - acc
  pull_request: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Pint (lint)
        run: vendor/bin/pint --test || exit 1

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Use CI environment
        run: |
          if [[ "${GITHUB_REF}" != "refs/heads/dev" ]]; then
            cp .env.ci .env
          fi

      - name: Generate app key
        run: php artisan key:generate

      # Alleen DB + migraties voor test, acc, main
      - name: Setup DB and migrate
        if: github.ref != 'refs/heads/dev'
        run: |
          sudo service mysql start || true
          for i in {1..15}; do
            if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
              echo "DB is up!"
              break
            fi
            echo "Waiting for DB..."
            sleep 5
          done
          php artisan migrate --force

      - name: Run tests
        run: php artisan test

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/acc' || github.ref == 'refs/heads/test'
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            SERVICE_ID=${{ secrets.RENDER_SERVICE_ID_PROD }}
          elif [[ "${GITHUB_REF}" == "refs/heads/acc" ]]; then
            SERVICE_ID=${{ secrets.RENDER_SERVICE_ID_ACC }}
          elif [[ "${GITHUB_REF}" == "refs/heads/test" ]]; then
            SERVICE_ID=${{ secrets.RENDER_SERVICE_ID_TEST }}
          fi

          echo "Deploying branch ${GITHUB_REF} to service $SERVICE_ID"
          curl -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
               -H "Accept: application/json" \
               -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
