name: CI/CD Laravel

on:
  push:
    branches:
      - main
      - dev
      - test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Run Pint (lint)
        run: vendor/bin/pint --test || exit 1

  test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: laravel_test_db
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U laravel -d laravel_test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo_pgsql
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Create .env file
        run: cp .env.example .env
      - name: Generate app key
        run: php artisan key:generate
      - name: Run migrations
        env:
          DB_CONNECTION: pgsql
          DB_HOST: postgres
          DB_PORT: 5432
          DB_DATABASE: laravel_test_db
          DB_USERNAME: laravel
          DB_PASSWORD: secret
        run: php artisan migrate --force
      - name: Run tests
        env:
          DB_CONNECTION: pgsql
          DB_HOST: postgres
          DB_PORT: 5432
          DB_DATABASE: laravel_test_db
          DB_USERNAME: laravel
          DB_PASSWORD: secret
        run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to Render
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            SERVICE_ID=${{ secrets.RENDER_SERVICE_ID_PROD }}
          elif [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            SERVICE_ID=${{ secrets.RENDER_SERVICE_ID_DEV }}
          elif [[ "${GITHUB_REF}" == "refs/heads/test" ]]; then
            SERVICE_ID=${{ secrets.RENDER_SERVICE_ID_TEST }}
          fi
          curl -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
               -H "Accept: application/json" \
               -H "Authorization: Bearer ${{ secr
