name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: laravel_songs_db_tk6i_user
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: laravel_songs_db_tk6i
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U laravel_songs_db_tk6i_user -d laravel_songs_db_tk6i"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_DATABASE: laravel_songs_db_tk6i
      DB_USERNAME: laravel_songs_db_tk6i_user
      DB_PASSWORD: secret

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Create .env file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Wait for DB
        run: |
          for i in {1..30}; do
            if pg_isready -h 127.0.0.1 -U laravel_songs_db_tk6i_user -d laravel_songs_db_tk6i; then
              echo "DB is up!"
              exit 0
            fi
            echo "Waiting for DB..."
            sleep 5
          done
          echo "DB did not start in time" >&2
          exit 1

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
