name: CI/CD Dev

on:
  push:
    branches:
      - dev

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: laravel
          POSTGRES_DB: laravel
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U laravel"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_pgsql, pgsql, bcmath, gd
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run migrations
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: laravel
          DB_USERNAME: laravel
          DB_PASSWORD: laravel
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test

      - name: Deploy to Render (Dev Service)
        if: success()
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_DEV_SERVICE_ID }}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
